<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable = ['title','path','parent'];
    public function delete(array $options=[])
    {
        $child = self::where('parent',$this->id);
        $child->delete();
        return parent::delete($options); // TODO: Change the autogenerated stub
    }
}
