<?php
namespace App\Repositories;
use App\Models\Portfolio;
class PortfoliosRepository extends \App\Repositories\Repository
{
    public function __construct (Portfolio $portfolio)
    {
        $this->model = $portfolio;
    }
    public function one($alias, $attr = array())
    {
        $portfolio = parent::one($alias, $attr); // TODO: Change the autogenerated stub
        if ($portfolio && $portfolio->img)
        {
            $portfolio->img = json_decode($portfolio->img);
        }
        return $portfolio;
    }
}
